package dev.haroldjose.familysharedlist.dataLayer.datasource.remote.account

import dev.haroldjose.familysharedlist.dataLayer.datasource.remote.mongoDb.IMongoDbDataApiDataSource
import dev.haroldjose.familysharedlist.dataLayer.dto.AccountDto

interface IAccountMongoDbDataApiDataSource: IMongoDbDataApiDataSource<AccountDto>